/*
 * SecretSanta API
 * Get and post persons and games
 *
 * OpenAPI spec version: 1.0
 * Contact: delona88@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * PersonGame
 */


public class PersonGame {
  @SerializedName("idGame")
  private Integer idGame = null;

  @SerializedName("receiverEmail")
  private String receiverEmail = null;

  @SerializedName("wishlist")
  private String wishlist = null;

  @SerializedName("active")
  private Boolean active = null;

  @SerializedName("arrayNaughtyListEmail")
  private List<String> arrayNaughtyListEmail = null;

  public PersonGame idGame(Integer idGame) {
    this.idGame = idGame;
    return this;
  }

   /**
   * Get idGame
   * @return idGame
  **/
  @Schema(description = "")
  public Integer getIdGame() {
    return idGame;
  }

  public void setIdGame(Integer idGame) {
    this.idGame = idGame;
  }

  public PersonGame receiverEmail(String receiverEmail) {
    this.receiverEmail = receiverEmail;
    return this;
  }

   /**
   * Get receiverEmail
   * @return receiverEmail
  **/
  @Schema(description = "")
  public String getReceiverEmail() {
    return receiverEmail;
  }

  public void setReceiverEmail(String receiverEmail) {
    this.receiverEmail = receiverEmail;
  }

  public PersonGame wishlist(String wishlist) {
    this.wishlist = wishlist;
    return this;
  }

   /**
   * Get wishlist
   * @return wishlist
  **/
  @Schema(description = "")
  public String getWishlist() {
    return wishlist;
  }

  public void setWishlist(String wishlist) {
    this.wishlist = wishlist;
  }

  public PersonGame active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @Schema(description = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public PersonGame arrayNaughtyListEmail(List<String> arrayNaughtyListEmail) {
    this.arrayNaughtyListEmail = arrayNaughtyListEmail;
    return this;
  }

  public PersonGame addArrayNaughtyListEmailItem(String arrayNaughtyListEmailItem) {
    if (this.arrayNaughtyListEmail == null) {
      this.arrayNaughtyListEmail = new ArrayList<>();
    }
    this.arrayNaughtyListEmail.add(arrayNaughtyListEmailItem);
    return this;
  }

   /**
   * Get arrayNaughtyListEmail
   * @return arrayNaughtyListEmail
  **/
  @Schema(description = "")
  public List<String> getArrayNaughtyListEmail() {
    return arrayNaughtyListEmail;
  }

  public void setArrayNaughtyListEmail(List<String> arrayNaughtyListEmail) {
    this.arrayNaughtyListEmail = arrayNaughtyListEmail;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonGame personGame = (PersonGame) o;
    return Objects.equals(this.idGame, personGame.idGame) &&
        Objects.equals(this.receiverEmail, personGame.receiverEmail) &&
        Objects.equals(this.wishlist, personGame.wishlist) &&
        Objects.equals(this.active, personGame.active) &&
        Objects.equals(this.arrayNaughtyListEmail, personGame.arrayNaughtyListEmail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idGame, receiverEmail, wishlist, active, arrayNaughtyListEmail);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonGame {\n");
    
    sb.append("    idGame: ").append(toIndentedString(idGame)).append("\n");
    sb.append("    receiverEmail: ").append(toIndentedString(receiverEmail)).append("\n");
    sb.append("    wishlist: ").append(toIndentedString(wishlist)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    arrayNaughtyListEmail: ").append(toIndentedString(arrayNaughtyListEmail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
