/*
 * SecretSanta API
 * Get and post persons and games
 *
 * OpenAPI spec version: 1.0
 * Contact: delona88@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * SecretSantaGame
 */


public class SecretSantaGame {
  @SerializedName("idOfGame")
  private Integer idOfGame = null;

  @SerializedName("played")
  private Boolean played = null;

  @SerializedName("participantsEmail")
  private List<String> participantsEmail = null;

  public SecretSantaGame idOfGame(Integer idOfGame) {
    this.idOfGame = idOfGame;
    return this;
  }

   /**
   * Get idOfGame
   * @return idOfGame
  **/
  @Schema(description = "")
  public Integer getIdOfGame() {
    return idOfGame;
  }

  public void setIdOfGame(Integer idOfGame) {
    this.idOfGame = idOfGame;
  }

  public SecretSantaGame played(Boolean played) {
    this.played = played;
    return this;
  }

   /**
   * Get played
   * @return played
  **/
  @Schema(description = "")
  public Boolean isPlayed() {
    return played;
  }

  public void setPlayed(Boolean played) {
    this.played = played;
  }

  public SecretSantaGame participantsEmail(List<String> participantsEmail) {
    this.participantsEmail = participantsEmail;
    return this;
  }

  public SecretSantaGame addParticipantsEmailItem(String participantsEmailItem) {
    if (this.participantsEmail == null) {
      this.participantsEmail = new ArrayList<>();
    }
    this.participantsEmail.add(participantsEmailItem);
    return this;
  }

   /**
   * Get participantsEmail
   * @return participantsEmail
  **/
  @Schema(description = "")
  public List<String> getParticipantsEmail() {
    return participantsEmail;
  }

  public void setParticipantsEmail(List<String> participantsEmail) {
    this.participantsEmail = participantsEmail;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SecretSantaGame secretSantaGame = (SecretSantaGame) o;
    return Objects.equals(this.idOfGame, secretSantaGame.idOfGame) &&
        Objects.equals(this.played, secretSantaGame.played) &&
        Objects.equals(this.participantsEmail, secretSantaGame.participantsEmail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idOfGame, played, participantsEmail);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SecretSantaGame {\n");
    
    sb.append("    idOfGame: ").append(toIndentedString(idOfGame)).append("\n");
    sb.append("    played: ").append(toIndentedString(played)).append("\n");
    sb.append("    participantsEmail: ").append(toIndentedString(participantsEmail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
